# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuittest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_suittest(self):
    # Test name: Suit-test
    # Step # | name | target | value
    # 1 | open | https://trainme.trainme-staging.com/ | 
    self.driver.get("https://trainme.trainme-staging.com/")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | xpath=//input[@name='email'] | 
    self.driver.find_element(By.XPATH, "//input[@name=\'email\']").click()
    # 4 | type | xpath=//input[@name='email'] | qa@trainme.cloud
    self.driver.find_element(By.XPATH, "//input[@name=\'email\']").send_keys("qa@trainme.cloud")
    # 5 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 6 | type | name=password | qwerty
    self.driver.find_element(By.NAME, "password").send_keys("qwerty")
    # 7 | click | css=.leading-6 | 
    self.driver.find_element(By.CSS_SELECTOR, ".leading-6").click()
    # 8 | mouseOver | linkText=Inicio | 
    element = self.driver.find_element(By.LINK_TEXT, "Inicio")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | linkText=Usuarios | 
    self.driver.find_element(By.LINK_TEXT, "Usuarios").click()
    # 10 | mouseOver | linkText=Grupos | 
    element = self.driver.find_element(By.LINK_TEXT, "Grupos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOver | linkText=Grupos | 
    element = self.driver.find_element(By.LINK_TEXT, "Grupos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | linkText=Grupos | 
    self.driver.find_element(By.LINK_TEXT, "Grupos").click()
    # 13 | mouseOver | linkText=Grupos | 
    element = self.driver.find_element(By.LINK_TEXT, "Grupos")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | linkText=Grupos | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | linkText=Cursos | 
    self.driver.find_element(By.LINK_TEXT, "Cursos").click()
    # 16 | mouseOver | linkText=Rutas | 
    element = self.driver.find_element(By.LINK_TEXT, "Rutas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | click | linkText=Rutas | 
    self.driver.find_element(By.LINK_TEXT, "Rutas").click()
    # 18 | click | linkText=Gamificación | 
    self.driver.find_element(By.LINK_TEXT, "Gamificación").click()
    # 19 | mouseOver | linkText=Reportes | 
    element = self.driver.find_element(By.LINK_TEXT, "Reportes")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | click | linkText=Reportes | 
    self.driver.find_element(By.LINK_TEXT, "Reportes").click()
    # 21 | click | linkText=Inicio | 
    self.driver.find_element(By.LINK_TEXT, "Inicio").click()
  
